# Generated by Django 4.0.4 on 2022-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('description', models.TextField(default='SOME STRING', max_length=1024)),
                ('price', models.FloatField()),
                ('picture', models.TextField()),
            ],
        ),
    ]
